stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile.ubuntu18.04
      buildContext: .
      tag: longbao128/gpu-monitor
      pushRemote: true
      registry: index.docker.io
timeout: 60
branch:
  include:
  - master
notification: {}
